[package]
name = "wnfs"
version = "0.1.19"
description = "WebNative filesystem core implementation"
keywords = ["wnfs", "webnative", "ipfs", "decentralisation"]
categories = [
  "filesystem",
  "cryptography",
  "web-programming",
  "wasm",
]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
repository = "https://github.com/wnfs-wg/rs-wnfs/tree/main/wnfs"
homepage = "https://fission.codes"
authors = ["The Fission Authors"]

[dependencies]
aes-gcm = "0.10"
aes-kw = { version = "0.2", features = ["alloc"] }
anyhow = "1.0"
async-once-cell = "0.4"
async-recursion = "1.0"
async-stream = "0.3"
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
futures = "0.3"
libipld = { version = "0.16", features = ["dag-cbor", "derive", "serde-codec"] }
multihash = "0.18"
once_cell = "1.16"
proptest = { version = "1.1", optional = true }
rand_core = "0.6"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["rc"] }
sha3 = "0.10"
skip_ratchet = { version = "0.2", features = ["serde"], git = "https://github.com/wnfs-wg/rs-skip-ratchet.git", branch = "matheus23/fix-serialization" }
thiserror = "1.0"
wnfs-common = { path = "../wnfs-common", version = "0.1.19" }
wnfs-hamt = { path = "../wnfs-hamt", version = "0.1.19" }
wnfs-nameaccumulator = { path = "../wnfs-nameaccumulator", version = "0.1.19" }
wnfs-namefilter = { path = "../wnfs-namefilter", version = "0.1.19" }
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[dev-dependencies]
async-std = { version = "1.11", features = ["attributes"] }
env_logger = "0.10"
proptest = "1.1"
rand = "0.8"
rand_chacha = "0.3.1"
rsa = "0.8"
sha2 = "0.10"
test-log = "0.2"
test-strategy = "0.3"
tokio = { version = "1.0", features = ["full"] }

[lib]
name = "wnfs"
path = "src/lib.rs"

[features]
default = []
wasm = []
