ignore:
  - "*/test/*"
  - "crates/wasm/*"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

github_checks:
  annotations: false

status:
    project:
      default:
        threshold: 5%
