[package]
name = "wnfs-bench"
version = "0.1.14"
description = "WNFS Benchmarks"
publish = false
edition = "2021"

[dev-dependencies]
async-std = { version = "1.11", features = ["attributes"] }
criterion = { version = "0.4", features = ["async_std"] }
proptest = "1.1"
wnfs = { path = "../wnfs", features = ["test_strategies"] }
wnfs-common = { version = "0.1.14", path = "../wnfs-common", features = ["test_strategies"] }
wnfs-hamt = { version = "0.1.14", path = "../wnfs-hamt", features = ["test_strategies"] }

[[bench]]
name = "hamt"
harness = false
path = "hamt.rs"

[[bench]]
name = "namefilter"
harness = false
path = "namefilter.rs"
