name: 🧪 Tests and Checks

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  rust-tests-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Project
        uses: Swatinem/rust-cache@v1.3.0

      - name: Check Format
        run: cargo fmt --all -- --check

      - name: Run Linter
        run: cargo clippy --all -- -D warnings

      - name: Run Tests
        run: cargo test --all

  wasm-js-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./crates/wasm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Project (JavaScript)
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache Project (Rust)
        uses: Swatinem/rust-cache@v1.3.0

      - name: Setup WebAssembly Toolchain
        run: rustup target add wasm32-unknown-unknown && cargo install wasm-pack

      - name: Install Node Dependencies
        run: yarn

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: yarn playwright test

      # - name: Upload Playwright Report
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30

